### ISSUE TITLE
Characters not counted in RTE for Umbraco 8.13.0

### ISSUE THREAD

**Issue by hfloyd** [tomvanenckevort/Codery.TextCount#10]
I was really excited to find this lovely package, since it is providing the functionality I was looking for, unfortunately, the counter doesn't seem to be working, at least in RTEs in Umbraco 8.13.0:
![image](https://user-images.githubusercontent.com/1252593/119766615-57ebda80-be83-11eb-9fa2-48bbbd78d726.png)

This does work for a basic textstring:
![image](https://user-images.githubusercontent.com/1252593/119766839-b9ac4480-be83-11eb-971f-0b6a024e864a.png)

I'm not sure if the structure of the RTE changed since your last updated for Umbraco 8.2...
This is the back-office HTML:
![image](https://user-images.githubusercontent.com/1252593/119767160-5b339600-be84-11eb-9759-ab1dbd3a062a.png)

**Comment by tomvanenckevort** [comment]
Yes, it might well be the case that some of the HTML tags have changed in newer versions of Umbraco. 
Let me try it out and see if I can update the code to handle the new versions as well.

**Comment by hfloyd** [comment]
Thanks, @tomvanenckevort I really appreciate it. 🙂

**Comment by tomvanenckevort** [comment]
This has been fixed in v2.0.4 that is now available on Nuget and Our.

**Comment by hfloyd** [comment]
Thanks, @tomvanenckevort! 👏

I've verified that it now works in 8.13.0:
![image](https://user-images.githubusercontent.com/1252593/120509422-7a578980-c396-11eb-81ba-328c36f5faa1.png)
![image](https://user-images.githubusercontent.com/1252593/120509497-8e9b8680-c396-11eb-9546-d4330cfda7af.png)
![image](https://user-images.githubusercontent.com/1252593/120509577-a07d2980-c396-11eb-81e4-016ae8fe9f97.png)
