### ISSUE TITLE
Feature: Any plans for a v8 version?

### ISSUE THREAD

**Issue by ZacP** [tomvanenckevort/Codery.TextCount#7]
Any plans for a v8 version?

**Comment by tomvanenckevort** [comment]
Hi @ZacP,

Yes, I probably should make a start with that. Thanks for reminding me 😃

**Comment by ZacP** [comment]
That sounds great, Tom!

**Comment by ZacP** [comment]
Hi Tom,

This is looking good.  I found a bug for the TextCount using an RTE (for 8.2).

textcount.directive.js, line 77
change 
                var isTinyMCE = $el.parent().hasClass('umb-rte'); 
to
                var isTinyMCE = $el.parent().hasClass('umb-rte-editor-con');

The v8 editor has a different class wrapper.  Once I found this, it seems to work correctly with the RTE.

Thanks!

**Comment by tomvanenckevort** [comment]
Hi @ZacP,

Yes, I forgot to test it in 8.2 before releasing it last week.

Thanks for your suggested fix. I've used that to add a fix that supports both 8.1 and 8.2, and just released a new version (v2.0.3).
