### ISSUE TITLE
"Our" Package missing files

### ISSUE THREAD

**Issue by hfloyd** [tomvanenckevort/Codery.TextCount#8]
When installing via Our Package (version 2.0.3 from https://our.umbraco.com/packages/backoffice-extensions/text-count/), then attempting to create a DataType, it seems some files are missing:

![image](https://user-images.githubusercontent.com/1252593/119760099-616f4580-be77-11eb-9cfa-b80e6d8fdf13.png)

**Comment by tomvanenckevort** [comment]
It looks like some of the paths might have changed in newer Umbraco versions. 
I'll have a look and see if I need to update where some of the files get copied to.

**Comment by tomvanenckevort** [comment]
This has been fixed in v2.0.4 that is now available on Our.

**Comment by hfloyd** [comment]
The updated package installed beautifully!
